# Generated by Django 3.0.8 on 2020-08-06 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('added_by', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('ram_needed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('total_ram', models.IntegerField()),
                ('processes', models.ManyToManyField(blank=True, to='jobs.process')),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_status', models.CharField(choices=[('started', 'Job Started'), ('queued', 'Job is Yet to start'), ('error', 'Job stopped because of error in processing'), ('internal_error', 'Job stopped because of an internal error in the system'), ('finished', 'Job is finished')], default='queued', max_length=25)),
                ('queue_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('job_arguments', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=50)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.process')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.node')),
            ],
        ),
    ]
