# Generated by Django 3.0.8 on 2020-08-06 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_status',
        ),
        migrations.AddField(
            model_name='job',
            name='ingest_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('started', 'Job Started'), ('queued', 'Job is Yet to start'), ('error', 'Job stopped because of error in processing'), ('internal_error', 'Job stopped because of an internal error in the system'), ('finished', 'Job is finished'), ('ingested', 'Job is recieved by system')], default='ingested', max_length=25),
        ),
        migrations.AlterField(
            model_name='job',
            name='queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.node'),
        ),
        migrations.AlterField(
            model_name='job',
            name='queue_time',
            field=models.DateTimeField(null=True),
        ),
    ]
